-- MySQL Script generated by MySQL Workbench
-- 02/26/15 08:13:56
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Videojuego`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Videojuego` (
  `id_Videojuego` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  `precio_dia` INT NULL,
  `consola` VARCHAR(45) NULL,
  `stock` VARCHAR(45) NULL,
  `imagen` VARCHAR(45) NULL,
  PRIMARY KEY (`id_Videojuego`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `cedula` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `telefono` DOUBLE NULL,
  PRIMARY KEY (`cedula`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`prestamo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`prestamo` (
  `id_Videojuego` INT NOT NULL,
  `id_Cliente` INT NOT NULL,
  `id_prestamo` INT NOT NULL,
  PRIMARY KEY (`id_Videojuego`, `id_Cliente`, `id_prestamo`),
  INDEX `fk_Videojuego_has_Cliente_Cliente1_idx` (`id_Cliente` ASC),
  INDEX `fk_Videojuego_has_Cliente_Videojuego_idx` (`id_Videojuego` ASC),
  CONSTRAINT `fk_Videojuego_has_Cliente_Videojuego`
    FOREIGN KEY (`id_Videojuego`)
    REFERENCES `mydb`.`Videojuego` (`id_Videojuego`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Videojuego_has_Cliente_Cliente1`
    FOREIGN KEY (`id_Cliente`)
    REFERENCES `mydb`.`Cliente` (`cedula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
